apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: jenkins-ingress-ssl
  backend:
    serviceName: cd-jenkins
    servicePort: 8080
